//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b20130806.1801 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.18 at 09:33:10 AM EET 
//


package gov.nih.nlm.ncbi.snp.docsum;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="geneId" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="symbol" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="mrnaAcc" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="mrnaVer" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="protAcc" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="protVer" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="fxnClass">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="locus-region"/>
 *             &lt;enumeration value="coding-unknown"/>
 *             &lt;enumeration value="synonymous-codon"/>
 *             &lt;enumeration value="non-synonymous-codon"/>
 *             &lt;enumeration value="mrna-utr"/>
 *             &lt;enumeration value="intron-variant"/>
 *             &lt;enumeration value="splice-region-variant"/>
 *             &lt;enumeration value="reference"/>
 *             &lt;enumeration value="coding-exception"/>
 *             &lt;enumeration value="coding-sequence-variant"/>
 *             &lt;enumeration value="nc-transcript-variant"/>
 *             &lt;enumeration value="downstream-variant-500B"/>
 *             &lt;enumeration value="upstream-variant-2KB"/>
 *             &lt;enumeration value="nonsense"/>
 *             &lt;enumeration value="missense"/>
 *             &lt;enumeration value="frameshift-variant"/>
 *             &lt;enumeration value="utr-variant-3-prime"/>
 *             &lt;enumeration value="utr-variant-5-prime"/>
 *             &lt;enumeration value="splice-acceptor-variant"/>
 *             &lt;enumeration value="splice-donor-variant"/>
 *             &lt;enumeration value="cds-indel"/>
 *             &lt;enumeration value="stop-gained"/>
 *             &lt;enumeration value="stop-lost"/>
 *             &lt;enumeration value="complex-change-in-transcript"/>
 *             &lt;enumeration value="incomplete-terminal-codon-variant"/>
 *             &lt;enumeration value="nmd-transcript-variant"/>
 *             &lt;enumeration value="mature-miRNA-variant"/>
 *             &lt;enumeration value="upstream-variant-5KB"/>
 *             &lt;enumeration value="downstream-variant-5KB"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="readingFrame" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="allele" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="residue" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="aaPosition" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="mrnaPosition" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "FxnSet")
public class FxnSet {

    @XmlAttribute(name = "geneId")
    protected Integer geneId;
    @XmlAttribute(name = "symbol")
    protected String symbol;
    @XmlAttribute(name = "mrnaAcc")
    protected String mrnaAcc;
    @XmlAttribute(name = "mrnaVer")
    protected Integer mrnaVer;
    @XmlAttribute(name = "protAcc")
    protected String protAcc;
    @XmlAttribute(name = "protVer")
    protected Integer protVer;
    @XmlAttribute(name = "fxnClass")
    protected String fxnClass;
    @XmlAttribute(name = "readingFrame")
    protected Integer readingFrame;
    @XmlAttribute(name = "allele")
    protected String allele;
    @XmlAttribute(name = "residue")
    protected String residue;
    @XmlAttribute(name = "aaPosition")
    protected Integer aaPosition;
    @XmlAttribute(name = "mrnaPosition")
    protected Integer mrnaPosition;

    /**
     * Gets the value of the geneId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getGeneId() {
        return geneId;
    }

    /**
     * Sets the value of the geneId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setGeneId(Integer value) {
        this.geneId = value;
    }

    /**
     * Gets the value of the symbol property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSymbol() {
        return symbol;
    }

    /**
     * Sets the value of the symbol property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSymbol(String value) {
        this.symbol = value;
    }

    /**
     * Gets the value of the mrnaAcc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMrnaAcc() {
        return mrnaAcc;
    }

    /**
     * Sets the value of the mrnaAcc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMrnaAcc(String value) {
        this.mrnaAcc = value;
    }

    /**
     * Gets the value of the mrnaVer property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMrnaVer() {
        return mrnaVer;
    }

    /**
     * Sets the value of the mrnaVer property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMrnaVer(Integer value) {
        this.mrnaVer = value;
    }

    /**
     * Gets the value of the protAcc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProtAcc() {
        return protAcc;
    }

    /**
     * Sets the value of the protAcc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProtAcc(String value) {
        this.protAcc = value;
    }

    /**
     * Gets the value of the protVer property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getProtVer() {
        return protVer;
    }

    /**
     * Sets the value of the protVer property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setProtVer(Integer value) {
        this.protVer = value;
    }

    /**
     * Gets the value of the fxnClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFxnClass() {
        return fxnClass;
    }

    /**
     * Sets the value of the fxnClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFxnClass(String value) {
        this.fxnClass = value;
    }

    /**
     * Gets the value of the readingFrame property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getReadingFrame() {
        return readingFrame;
    }

    /**
     * Sets the value of the readingFrame property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setReadingFrame(Integer value) {
        this.readingFrame = value;
    }

    /**
     * Gets the value of the allele property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAllele() {
        return allele;
    }

    /**
     * Sets the value of the allele property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAllele(String value) {
        this.allele = value;
    }

    /**
     * Gets the value of the residue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResidue() {
        return residue;
    }

    /**
     * Sets the value of the residue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResidue(String value) {
        this.residue = value;
    }

    /**
     * Gets the value of the aaPosition property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getAaPosition() {
        return aaPosition;
    }

    /**
     * Sets the value of the aaPosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setAaPosition(Integer value) {
        this.aaPosition = value;
    }

    /**
     * Gets the value of the mrnaPosition property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMrnaPosition() {
        return mrnaPosition;
    }

    /**
     * Sets the value of the mrnaPosition property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMrnaPosition(Integer value) {
        this.mrnaPosition = value;
    }

}
