//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.25 at 09:13:08 AM EET 
//

package gov.nih.nlm.ncbi.snp.docsum;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *       &lt;attribute name="urlId" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="resourceName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="resourceId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType( XmlAccessType.FIELD)
@XmlType( name = "", propOrder = {"value"})
@XmlRootElement( name = "BaseURL")
public class BaseURL {

	@XmlValue
	protected String value;
	@XmlAttribute( name = "urlId")
	protected Integer urlId;
	@XmlAttribute( name = "resourceName")
	protected String resourceName;
	@XmlAttribute( name = "resourceId")
	protected String resourceId;

	/**
	 * Gets the value of the value property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getValue() {

		return value;
	}

	/**
	 * Sets the value of the value property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setValue( String value) {

		this.value = value;
	}

	/**
	 * Gets the value of the urlId property.
	 * 
	 * @return possible object is {@link Integer }
	 * 
	 */
	public Integer getUrlId() {

		return urlId;
	}

	/**
	 * Sets the value of the urlId property.
	 * 
	 * @param value
	 *            allowed object is {@link Integer }
	 * 
	 */
	public void setUrlId( Integer value) {

		this.urlId = value;
	}

	/**
	 * Gets the value of the resourceName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getResourceName() {

		return resourceName;
	}

	/**
	 * Sets the value of the resourceName property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setResourceName( String value) {

		this.resourceName = value;
	}

	/**
	 * Gets the value of the resourceId property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getResourceId() {

		return resourceId;
	}

	/**
	 * Sets the value of the resourceId property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setResourceId( String value) {

		this.resourceId = value;
	}

}
