//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.25 at 09:13:08 AM EET 
//

package gov.nih.nlm.ncbi.snp.docsum;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.ncbi.nlm.nih.gov/SNP/docsum}MapLoc" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="componentType">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="contig"/>
 *             &lt;enumeration value="mrna"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="ctgId" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="accession" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="chromosome" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="start" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="end" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="orientation">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="fwd"/>
 *             &lt;enumeration value="rev"/>
 *             &lt;enumeration value="unknown"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="gi" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="groupTerm" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="contigLabel" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "mapLoc" })
@XmlRootElement(name = "Component")
public class Component {

	@XmlElement(name = "MapLoc", required = true)
	protected List<MapLoc> mapLoc;
	@XmlAttribute(name = "componentType")
	protected String componentType;
	@XmlAttribute(name = "ctgId")
	protected Integer ctgId;
	@XmlAttribute(name = "accession")
	protected String accession;
	@XmlAttribute(name = "name")
	protected String name;
	@XmlAttribute(name = "chromosome")
	protected String chromosome;
	@XmlAttribute(name = "start")
	protected Integer start;
	@XmlAttribute(name = "end")
	protected Integer end;
	@XmlAttribute(name = "orientation")
	protected String orientation;
	@XmlAttribute(name = "gi")
	protected String gi;
	@XmlAttribute(name = "groupTerm")
	protected String groupTerm;
	@XmlAttribute(name = "contigLabel")
	protected String contigLabel;

	/**
	 * Gets the value of the mapLoc property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the mapLoc property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getMapLoc().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link MapLoc }
	 * 
	 * 
	 */
	public List<MapLoc> getMapLoc() {
		if (mapLoc == null) {
			mapLoc = new ArrayList<MapLoc>();
		}
		return this.mapLoc;
	}

	/**
	 * Gets the value of the componentType property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getComponentType() {
		return componentType;
	}

	/**
	 * Sets the value of the componentType property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setComponentType(String value) {
		this.componentType = value;
	}

	/**
	 * Gets the value of the ctgId property.
	 * 
	 * @return possible object is {@link Integer }
	 * 
	 */
	public Integer getCtgId() {
		return ctgId;
	}

	/**
	 * Sets the value of the ctgId property.
	 * 
	 * @param value
	 *            allowed object is {@link Integer }
	 * 
	 */
	public void setCtgId(Integer value) {
		this.ctgId = value;
	}

	/**
	 * Gets the value of the accession property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getAccession() {
		return accession;
	}

	/**
	 * Sets the value of the accession property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setAccession(String value) {
		this.accession = value;
	}

	/**
	 * Gets the value of the name property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getName() {
		return name;
	}

	/**
	 * Sets the value of the name property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setName(String value) {
		this.name = value;
	}

	/**
	 * Gets the value of the chromosome property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getChromosome() {
		return chromosome;
	}

	/**
	 * Sets the value of the chromosome property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setChromosome(String value) {
		this.chromosome = value;
	}

	/**
	 * Gets the value of the start property.
	 * 
	 * @return possible object is {@link Integer }
	 * 
	 */
	public Integer getStart() {
		return start;
	}

	/**
	 * Sets the value of the start property.
	 * 
	 * @param value
	 *            allowed object is {@link Integer }
	 * 
	 */
	public void setStart(Integer value) {
		this.start = value;
	}

	/**
	 * Gets the value of the end property.
	 * 
	 * @return possible object is {@link Integer }
	 * 
	 */
	public Integer getEnd() {
		return end;
	}

	/**
	 * Sets the value of the end property.
	 * 
	 * @param value
	 *            allowed object is {@link Integer }
	 * 
	 */
	public void setEnd(Integer value) {
		this.end = value;
	}

	/**
	 * Gets the value of the orientation property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getOrientation() {
		return orientation;
	}

	/**
	 * Sets the value of the orientation property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setOrientation(String value) {
		this.orientation = value;
	}

	/**
	 * Gets the value of the gi property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getGi() {
		return gi;
	}

	/**
	 * Sets the value of the gi property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setGi(String value) {
		this.gi = value;
	}

	/**
	 * Gets the value of the groupTerm property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getGroupTerm() {
		return groupTerm;
	}

	/**
	 * Sets the value of the groupTerm property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setGroupTerm(String value) {
		this.groupTerm = value;
	}

	/**
	 * Gets the value of the contigLabel property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getContigLabel() {
		return contigLabel;
	}

	/**
	 * Sets the value of the contigLabel property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setContigLabel(String value) {
		this.contigLabel = value;
	}

}
