//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.24 at 04:17:33 PM EET 
//


package gov.nih.nlm.ncbi.snp.docsum;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the gov.nih.nlm.ncbi.snp.docsum package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: gov.nih.nlm.ncbi.snp.docsum
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Ss }
     * 
     */
    public Ss createSs() {
        return new Ss();
    }

    /**
     * Create an instance of {@link Assay }
     * 
     */
    public Assay createAssay() {
        return new Assay();
    }

    /**
     * Create an instance of {@link ExchangeSet }
     * 
     */
    public ExchangeSet createExchangeSet() {
        return new ExchangeSet();
    }

    /**
     * Create an instance of {@link Rs }
     * 
     */
    public Rs createRs() {
        return new Rs();
    }

    /**
     * Create an instance of {@link Assembly }
     * 
     */
    public Assembly createAssembly() {
        return new Assembly();
    }

    /**
     * Create an instance of {@link Ss.Sequence }
     * 
     */
    public Ss.Sequence createSsSequence() {
        return new Ss.Sequence();
    }

    /**
     * Create an instance of {@link Assay.Method }
     * 
     */
    public Assay.Method createAssayMethod() {
        return new Assay.Method();
    }

    /**
     * Create an instance of {@link Assay.Taxonomy }
     * 
     */
    public Assay.Taxonomy createAssayTaxonomy() {
        return new Assay.Taxonomy();
    }

    /**
     * Create an instance of {@link ExchangeSet.SourceDatabase }
     * 
     */
    public ExchangeSet.SourceDatabase createExchangeSetSourceDatabase() {
        return new ExchangeSet.SourceDatabase();
    }

    /**
     * Create an instance of {@link Rs.Het }
     * 
     */
    public Rs.Het createRsHet() {
        return new Rs.Het();
    }

    /**
     * Create an instance of {@link Rs.Validation }
     * 
     */
    public Rs.Validation createRsValidation() {
        return new Rs.Validation();
    }

    /**
     * Create an instance of {@link Rs.Create }
     * 
     */
    public Rs.Create createRsCreate() {
        return new Rs.Create();
    }

    /**
     * Create an instance of {@link Rs.Update }
     * 
     */
    public Rs.Update createRsUpdate() {
        return new Rs.Update();
    }

    /**
     * Create an instance of {@link Rs.Sequence }
     * 
     */
    public Rs.Sequence createRsSequence() {
        return new Rs.Sequence();
    }

    /**
     * Create an instance of {@link Component }
     * 
     */
    public Component createComponent() {
        return new Component();
    }

    /**
     * Create an instance of {@link MapLoc }
     * 
     */
    public MapLoc createMapLoc() {
        return new MapLoc();
    }

    /**
     * Create an instance of {@link FxnSet }
     * 
     */
    public FxnSet createFxnSet() {
        return new FxnSet();
    }

    /**
     * Create an instance of {@link Assembly.SnpStat }
     * 
     */
    public Assembly.SnpStat createAssemblySnpStat() {
        return new Assembly.SnpStat();
    }

    /**
     * Create an instance of {@link PrimarySequence }
     * 
     */
    public PrimarySequence createPrimarySequence() {
        return new PrimarySequence();
    }

    /**
     * Create an instance of {@link RsStruct }
     * 
     */
    public RsStruct createRsStruct() {
        return new RsStruct();
    }

    /**
     * Create an instance of {@link RsLinkout }
     * 
     */
    public RsLinkout createRsLinkout() {
        return new RsLinkout();
    }

    /**
     * Create an instance of {@link Rs.MergeHistory }
     * 
     */
    public Rs.MergeHistory createRsMergeHistory() {
        return new Rs.MergeHistory();
    }

    /**
     * Create an instance of {@link Rs.AlleleOrigin }
     * 
     */
    public Rs.AlleleOrigin createRsAlleleOrigin() {
        return new Rs.AlleleOrigin();
    }

    /**
     * Create an instance of {@link Rs.Phenotype }
     * 
     */
    public Rs.Phenotype createRsPhenotype() {
        return new Rs.Phenotype();
    }

    /**
     * Create an instance of {@link Rs.BioSource }
     * 
     */
    public Rs.BioSource createRsBioSource() {
        return new Rs.BioSource();
    }

    /**
     * Create an instance of {@link Rs.Frequency }
     * 
     */
    public Rs.Frequency createRsFrequency() {
        return new Rs.Frequency();
    }

    /**
     * Create an instance of {@link ExchangeSet.Query }
     * 
     */
    public ExchangeSet.Query createExchangeSetQuery() {
        return new ExchangeSet.Query();
    }

    /**
     * Create an instance of {@link ExchangeSet.Summary }
     * 
     */
    public ExchangeSet.Summary createExchangeSetSummary() {
        return new ExchangeSet.Summary();
    }

    /**
     * Create an instance of {@link BaseURL }
     * 
     */
    public BaseURL createBaseURL() {
        return new BaseURL();
    }

}
