//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.25 at 09:13:08 AM EET 
//

package gov.nih.nlm.ncbi.snp.docsum;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Het" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="type" use="required">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                       &lt;enumeration value="est"/>
 *                       &lt;enumeration value="obs"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *                 &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}float" />
 *                 &lt;attribute name="stdError" type="{http://www.w3.org/2001/XMLSchema}float" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Validation">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="otherPopBatchId" type="{http://www.w3.org/2001/XMLSchema}int" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="twoHit2AlleleBatchId" type="{http://www.w3.org/2001/XMLSchema}int" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="FrequencyClass" type="{http://www.w3.org/2001/XMLSchema}int" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="HapMapPhase" type="{http://www.w3.org/2001/XMLSchema}int" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="TGPPhase" type="{http://www.w3.org/2001/XMLSchema}int" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="SuspectEvidence" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="byCluster" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                 &lt;attribute name="byFrequency" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                 &lt;attribute name="byOtherPop" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                 &lt;attribute name="by2Hit2Allele" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                 &lt;attribute name="byHapMap" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                 &lt;attribute name="by1000G" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                 &lt;attribute name="suspect" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Create">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="build" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="date" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Update" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="build" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="date" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Sequence">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Seq5" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Observed" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Seq3" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="exemplarSs" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="ancestralAllele" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{http://www.ncbi.nlm.nih.gov/SNP/docsum}Ss" maxOccurs="unbounded"/>
 *         &lt;element ref="{http://www.ncbi.nlm.nih.gov/SNP/docsum}Assembly" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.ncbi.nlm.nih.gov/SNP/docsum}PrimarySequence" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.ncbi.nlm.nih.gov/SNP/docsum}RsStruct" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.ncbi.nlm.nih.gov/SNP/docsum}RsLinkout" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="MergeHistory" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="rsId" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="buildId" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="orientFlip" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="hgvs" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="AlleleOrigin" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>integer">
 *                 &lt;attribute name="allele" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Phenotype" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ClinicalSignificance" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="BioSource" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Genome" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="Origin" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Frequency" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="freq" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                 &lt;attribute name="allele" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="popId" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *                 &lt;attribute name="sampleSize" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="rsId" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="snpClass" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="snp"/>
 *             &lt;enumeration value="in-del"/>
 *             &lt;enumeration value="heterozygous"/>
 *             &lt;enumeration value="microsatellite"/>
 *             &lt;enumeration value="named-locus"/>
 *             &lt;enumeration value="no-variation"/>
 *             &lt;enumeration value="mixed"/>
 *             &lt;enumeration value="multinucleotide-polymorphism"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="snpType" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="notwithdrawn"/>
 *             &lt;enumeration value="artifact"/>
 *             &lt;enumeration value="gene-duplication"/>
 *             &lt;enumeration value="duplicate-submission"/>
 *             &lt;enumeration value="notspecified"/>
 *             &lt;enumeration value="ambiguous-location"/>
 *             &lt;enumeration value="low-map-quality"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="molType" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="genomic"/>
 *             &lt;enumeration value="cDNA"/>
 *             &lt;enumeration value="mito"/>
 *             &lt;enumeration value="chloro"/>
 *             &lt;enumeration value="unknown"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="validProbMin" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="validProbMax" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="genotype" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="bitField" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="taxId" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType( XmlAccessType.FIELD)
@XmlType( name = "", propOrder = {"het", "validation", "create", "update", "sequence", "ss", "assembly",
		"primarySequence", "rsStruct", "rsLinkout", "mergeHistory", "hgvs", "alleleOrigin", "phenotype", "bioSource",
		"frequency"})
@XmlRootElement( name = "Rs")
public class Rs {

	@XmlElement( name = "Het")
	protected Rs.Het het;
	@XmlElement( name = "Validation", required = true)
	protected Rs.Validation validation;
	@XmlElement( name = "Create", required = true)
	protected Rs.Create create;
	@XmlElement( name = "Update")
	protected Rs.Update update;
	@XmlElement( name = "Sequence", required = true)
	protected Rs.Sequence sequence;
	@XmlElement( name = "Ss", required = true)
	protected List<Ss> ss;
	@XmlElement( name = "Assembly")
	protected List<Assembly> assembly;
	@XmlElement( name = "PrimarySequence")
	protected List<PrimarySequence> primarySequence;
	@XmlElement( name = "RsStruct")
	protected List<RsStruct> rsStruct;
	@XmlElement( name = "RsLinkout")
	protected List<RsLinkout> rsLinkout;
	@XmlElement( name = "MergeHistory")
	protected List<Rs.MergeHistory> mergeHistory;
	protected List<String> hgvs;
	@XmlElement( name = "AlleleOrigin")
	protected List<Rs.AlleleOrigin> alleleOrigin;
	@XmlElement( name = "Phenotype")
	protected List<Rs.Phenotype> phenotype;
	@XmlElement( name = "BioSource")
	protected List<Rs.BioSource> bioSource;
	@XmlElement( name = "Frequency")
	protected List<Rs.Frequency> frequency;
	@XmlAttribute( name = "rsId", required = true)
	protected int rsId;
	@XmlAttribute( name = "snpClass", required = true)
	protected String snpClass;
	@XmlAttribute( name = "snpType", required = true)
	protected String snpType;
	@XmlAttribute( name = "molType", required = true)
	protected String molType;
	@XmlAttribute( name = "validProbMin")
	protected BigInteger validProbMin;
	@XmlAttribute( name = "validProbMax")
	protected BigInteger validProbMax;
	@XmlAttribute( name = "genotype")
	protected Boolean genotype;
	@XmlAttribute( name = "bitField")
	protected String bitField;
	@XmlAttribute( name = "taxId")
	protected Integer taxId;

	/**
	 * Gets the value of the het property.
	 * 
	 * @return possible object is {@link Rs.Het }
	 * 
	 */
	public Rs.Het getHet() {

		return het;
	}

	/**
	 * Sets the value of the het property.
	 * 
	 * @param value
	 *            allowed object is {@link Rs.Het }
	 * 
	 */
	public void setHet( Rs.Het value) {

		this.het = value;
	}

	/**
	 * Gets the value of the validation property.
	 * 
	 * @return possible object is {@link Rs.Validation }
	 * 
	 */
	public Rs.Validation getValidation() {

		return validation;
	}

	/**
	 * Sets the value of the validation property.
	 * 
	 * @param value
	 *            allowed object is {@link Rs.Validation }
	 * 
	 */
	public void setValidation( Rs.Validation value) {

		this.validation = value;
	}

	/**
	 * Gets the value of the create property.
	 * 
	 * @return possible object is {@link Rs.Create }
	 * 
	 */
	public Rs.Create getCreate() {

		return create;
	}

	/**
	 * Sets the value of the create property.
	 * 
	 * @param value
	 *            allowed object is {@link Rs.Create }
	 * 
	 */
	public void setCreate( Rs.Create value) {

		this.create = value;
	}

	/**
	 * Gets the value of the update property.
	 * 
	 * @return possible object is {@link Rs.Update }
	 * 
	 */
	public Rs.Update getUpdate() {

		return update;
	}

	/**
	 * Sets the value of the update property.
	 * 
	 * @param value
	 *            allowed object is {@link Rs.Update }
	 * 
	 */
	public void setUpdate( Rs.Update value) {

		this.update = value;
	}

	/**
	 * Gets the value of the sequence property.
	 * 
	 * @return possible object is {@link Rs.Sequence }
	 * 
	 */
	public Rs.Sequence getSequence() {

		return sequence;
	}

	/**
	 * Sets the value of the sequence property.
	 * 
	 * @param value
	 *            allowed object is {@link Rs.Sequence }
	 * 
	 */
	public void setSequence( Rs.Sequence value) {

		this.sequence = value;
	}

	/**
	 * Gets the value of the ss property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the ss property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getSs().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Ss }
	 * 
	 * 
	 */
	public List<Ss> getSs() {

		if( ss == null){
			ss = new ArrayList<Ss>();
		}
		return this.ss;
	}

	/**
	 * Gets the value of the assembly property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the assembly property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getAssembly().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Assembly }
	 * 
	 * 
	 */
	public List<Assembly> getAssembly() {

		if( assembly == null){
			assembly = new ArrayList<Assembly>();
		}
		return this.assembly;
	}

	/**
	 * Gets the value of the primarySequence property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the primarySequence property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getPrimarySequence().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link PrimarySequence }
	 * 
	 * 
	 */
	public List<PrimarySequence> getPrimarySequence() {

		if( primarySequence == null){
			primarySequence = new ArrayList<PrimarySequence>();
		}
		return this.primarySequence;
	}

	/**
	 * Gets the value of the rsStruct property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the rsStruct property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getRsStruct().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link RsStruct }
	 * 
	 * 
	 */
	public List<RsStruct> getRsStruct() {

		if( rsStruct == null){
			rsStruct = new ArrayList<RsStruct>();
		}
		return this.rsStruct;
	}

	/**
	 * Gets the value of the rsLinkout property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the rsLinkout property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getRsLinkout().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link RsLinkout }
	 * 
	 * 
	 */
	public List<RsLinkout> getRsLinkout() {

		if( rsLinkout == null){
			rsLinkout = new ArrayList<RsLinkout>();
		}
		return this.rsLinkout;
	}

	/**
	 * Gets the value of the mergeHistory property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the mergeHistory property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getMergeHistory().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link Rs.MergeHistory }
	 * 
	 * 
	 */
	public List<Rs.MergeHistory> getMergeHistory() {

		if( mergeHistory == null){
			mergeHistory = new ArrayList<Rs.MergeHistory>();
		}
		return this.mergeHistory;
	}

	/**
	 * Gets the value of the hgvs property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the hgvs property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getHgvs().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link String }
	 * 
	 * 
	 */
	public List<String> getHgvs() {

		if( hgvs == null){
			hgvs = new ArrayList<String>();
		}
		return this.hgvs;
	}

	/**
	 * Gets the value of the alleleOrigin property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the alleleOrigin property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getAlleleOrigin().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link Rs.AlleleOrigin }
	 * 
	 * 
	 */
	public List<Rs.AlleleOrigin> getAlleleOrigin() {

		if( alleleOrigin == null){
			alleleOrigin = new ArrayList<Rs.AlleleOrigin>();
		}
		return this.alleleOrigin;
	}

	/**
	 * Gets the value of the phenotype property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the phenotype property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getPhenotype().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link Rs.Phenotype }
	 * 
	 * 
	 */
	public List<Rs.Phenotype> getPhenotype() {

		if( phenotype == null){
			phenotype = new ArrayList<Rs.Phenotype>();
		}
		return this.phenotype;
	}

	/**
	 * Gets the value of the bioSource property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the bioSource property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getBioSource().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link Rs.BioSource }
	 * 
	 * 
	 */
	public List<Rs.BioSource> getBioSource() {

		if( bioSource == null){
			bioSource = new ArrayList<Rs.BioSource>();
		}
		return this.bioSource;
	}

	/**
	 * Gets the value of the frequency property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the frequency property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getFrequency().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link Rs.Frequency }
	 * 
	 * 
	 */
	public List<Rs.Frequency> getFrequency() {

		if( frequency == null){
			frequency = new ArrayList<Rs.Frequency>();
		}
		return this.frequency;
	}

	/**
	 * Gets the value of the rsId property.
	 * 
	 */
	public int getRsId() {

		return rsId;
	}

	/**
	 * Sets the value of the rsId property.
	 * 
	 */
	public void setRsId( int value) {

		this.rsId = value;
	}

	/**
	 * Gets the value of the snpClass property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSnpClass() {

		return snpClass;
	}

	/**
	 * Sets the value of the snpClass property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSnpClass( String value) {

		this.snpClass = value;
	}

	/**
	 * Gets the value of the snpType property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSnpType() {

		return snpType;
	}

	/**
	 * Sets the value of the snpType property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSnpType( String value) {

		this.snpType = value;
	}

	/**
	 * Gets the value of the molType property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getMolType() {

		return molType;
	}

	/**
	 * Sets the value of the molType property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setMolType( String value) {

		this.molType = value;
	}

	/**
	 * Gets the value of the validProbMin property.
	 * 
	 * @return possible object is {@link BigInteger }
	 * 
	 */
	public BigInteger getValidProbMin() {

		return validProbMin;
	}

	/**
	 * Sets the value of the validProbMin property.
	 * 
	 * @param value
	 *            allowed object is {@link BigInteger }
	 * 
	 */
	public void setValidProbMin( BigInteger value) {

		this.validProbMin = value;
	}

	/**
	 * Gets the value of the validProbMax property.
	 * 
	 * @return possible object is {@link BigInteger }
	 * 
	 */
	public BigInteger getValidProbMax() {

		return validProbMax;
	}

	/**
	 * Sets the value of the validProbMax property.
	 * 
	 * @param value
	 *            allowed object is {@link BigInteger }
	 * 
	 */
	public void setValidProbMax( BigInteger value) {

		this.validProbMax = value;
	}

	/**
	 * Gets the value of the genotype property.
	 * 
	 * @return possible object is {@link Boolean }
	 * 
	 */
	public Boolean isGenotype() {

		return genotype;
	}

	/**
	 * Sets the value of the genotype property.
	 * 
	 * @param value
	 *            allowed object is {@link Boolean }
	 * 
	 */
	public void setGenotype( Boolean value) {

		this.genotype = value;
	}

	/**
	 * Gets the value of the bitField property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getBitField() {

		return bitField;
	}

	/**
	 * Sets the value of the bitField property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setBitField( String value) {

		this.bitField = value;
	}

	/**
	 * Gets the value of the taxId property.
	 * 
	 * @return possible object is {@link Integer }
	 * 
	 */
	public Integer getTaxId() {

		return taxId;
	}

	/**
	 * Sets the value of the taxId property.
	 * 
	 * @param value
	 *            allowed object is {@link Integer }
	 * 
	 */
	public void setTaxId( Integer value) {

		this.taxId = value;
	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;simpleContent>
	 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>integer">
	 *       &lt;attribute name="allele" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *     &lt;/extension>
	 *   &lt;/simpleContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType( XmlAccessType.FIELD)
	@XmlType( name = "", propOrder = {"value"})
	public static class AlleleOrigin {

		@XmlValue
		protected BigInteger value;
		@XmlAttribute( name = "allele")
		protected String allele;

		/**
		 * Gets the value of the value property.
		 * 
		 * @return possible object is {@link BigInteger }
		 * 
		 */
		public BigInteger getValue() {

			return value;
		}

		/**
		 * Sets the value of the value property.
		 * 
		 * @param value
		 *            allowed object is {@link BigInteger }
		 * 
		 */
		public void setValue( BigInteger value) {

			this.value = value;
		}

		/**
		 * Gets the value of the allele property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getAllele() {

			return allele;
		}

		/**
		 * Sets the value of the allele property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setAllele( String value) {

			this.allele = value;
		}

	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="Genome" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
	 *         &lt;element name="Origin" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType( XmlAccessType.FIELD)
	@XmlType( name = "", propOrder = {"genome", "origin"})
	public static class BioSource {

		@XmlElement( name = "Genome")
		protected List<String> genome;
		@XmlElement( name = "Origin")
		protected List<String> origin;

		/**
		 * Gets the value of the genome property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a
		 * snapshot. Therefore any modification you make to the returned list
		 * will be present inside the JAXB object. This is why there is not a
		 * <CODE>set</CODE> method for the genome property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getGenome().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list
		 * {@link String }
		 * 
		 * 
		 */
		public List<String> getGenome() {

			if( genome == null){
				genome = new ArrayList<String>();
			}
			return this.genome;
		}

		/**
		 * Gets the value of the origin property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a
		 * snapshot. Therefore any modification you make to the returned list
		 * will be present inside the JAXB object. This is why there is not a
		 * <CODE>set</CODE> method for the origin property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getOrigin().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list
		 * {@link String }
		 * 
		 * 
		 */
		public List<String> getOrigin() {

			if( origin == null){
				origin = new ArrayList<String>();
			}
			return this.origin;
		}

	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;attribute name="build" type="{http://www.w3.org/2001/XMLSchema}int" />
	 *       &lt;attribute name="date" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType( XmlAccessType.FIELD)
	@XmlType( name = "")
	public static class Create {

		@XmlAttribute( name = "build")
		protected Integer build;
		@XmlAttribute( name = "date")
		protected String date;

		/**
		 * Gets the value of the build property.
		 * 
		 * @return possible object is {@link Integer }
		 * 
		 */
		public Integer getBuild() {

			return build;
		}

		/**
		 * Sets the value of the build property.
		 * 
		 * @param value
		 *            allowed object is {@link Integer }
		 * 
		 */
		public void setBuild( Integer value) {

			this.build = value;
		}

		/**
		 * Gets the value of the date property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getDate() {

			return date;
		}

		/**
		 * Sets the value of the date property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setDate( String value) {

			this.date = value;
		}

	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;attribute name="freq" type="{http://www.w3.org/2001/XMLSchema}double" />
	 *       &lt;attribute name="allele" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *       &lt;attribute name="popId" type="{http://www.w3.org/2001/XMLSchema}integer" />
	 *       &lt;attribute name="sampleSize" type="{http://www.w3.org/2001/XMLSchema}integer" />
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType( XmlAccessType.FIELD)
	@XmlType( name = "")
	public static class Frequency {

		@XmlAttribute( name = "freq")
		protected Double freq;
		@XmlAttribute( name = "allele")
		protected String allele;
		@XmlAttribute( name = "popId")
		protected BigInteger popId;
		@XmlAttribute( name = "sampleSize")
		protected BigInteger sampleSize;

		/**
		 * Gets the value of the freq property.
		 * 
		 * @return possible object is {@link Double }
		 * 
		 */
		public Double getFreq() {

			return freq;
		}

		/**
		 * Sets the value of the freq property.
		 * 
		 * @param value
		 *            allowed object is {@link Double }
		 * 
		 */
		public void setFreq( Double value) {

			this.freq = value;
		}

		/**
		 * Gets the value of the allele property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getAllele() {

			return allele;
		}

		/**
		 * Sets the value of the allele property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setAllele( String value) {

			this.allele = value;
		}

		/**
		 * Gets the value of the popId property.
		 * 
		 * @return possible object is {@link BigInteger }
		 * 
		 */
		public BigInteger getPopId() {

			return popId;
		}

		/**
		 * Sets the value of the popId property.
		 * 
		 * @param value
		 *            allowed object is {@link BigInteger }
		 * 
		 */
		public void setPopId( BigInteger value) {

			this.popId = value;
		}

		/**
		 * Gets the value of the sampleSize property.
		 * 
		 * @return possible object is {@link BigInteger }
		 * 
		 */
		public BigInteger getSampleSize() {

			return sampleSize;
		}

		/**
		 * Sets the value of the sampleSize property.
		 * 
		 * @param value
		 *            allowed object is {@link BigInteger }
		 * 
		 */
		public void setSampleSize( BigInteger value) {

			this.sampleSize = value;
		}

	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;attribute name="type" use="required">
	 *         &lt;simpleType>
	 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
	 *             &lt;enumeration value="est"/>
	 *             &lt;enumeration value="obs"/>
	 *           &lt;/restriction>
	 *         &lt;/simpleType>
	 *       &lt;/attribute>
	 *       &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}float" />
	 *       &lt;attribute name="stdError" type="{http://www.w3.org/2001/XMLSchema}float" />
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType( XmlAccessType.FIELD)
	@XmlType( name = "")
	public static class Het {

		@XmlAttribute( name = "type", required = true)
		protected String type;
		@XmlAttribute( name = "value", required = true)
		protected float value;
		@XmlAttribute( name = "stdError")
		protected Float stdError;

		/**
		 * Gets the value of the type property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getType() {

			return type;
		}

		/**
		 * Sets the value of the type property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setType( String value) {

			this.type = value;
		}

		/**
		 * Gets the value of the value property.
		 * 
		 */
		public float getValue() {

			return value;
		}

		/**
		 * Sets the value of the value property.
		 * 
		 */
		public void setValue( float value) {

			this.value = value;
		}

		/**
		 * Gets the value of the stdError property.
		 * 
		 * @return possible object is {@link Float }
		 * 
		 */
		public Float getStdError() {

			return stdError;
		}

		/**
		 * Sets the value of the stdError property.
		 * 
		 * @param value
		 *            allowed object is {@link Float }
		 * 
		 */
		public void setStdError( Float value) {

			this.stdError = value;
		}

	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;attribute name="rsId" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
	 *       &lt;attribute name="buildId" type="{http://www.w3.org/2001/XMLSchema}int" />
	 *       &lt;attribute name="orientFlip" type="{http://www.w3.org/2001/XMLSchema}boolean" />
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType( XmlAccessType.FIELD)
	@XmlType( name = "")
	public static class MergeHistory {

		@XmlAttribute( name = "rsId", required = true)
		protected int rsId;
		@XmlAttribute( name = "buildId")
		protected Integer buildId;
		@XmlAttribute( name = "orientFlip")
		protected Boolean orientFlip;

		/**
		 * Gets the value of the rsId property.
		 * 
		 */
		public int getRsId() {

			return rsId;
		}

		/**
		 * Sets the value of the rsId property.
		 * 
		 */
		public void setRsId( int value) {

			this.rsId = value;
		}

		/**
		 * Gets the value of the buildId property.
		 * 
		 * @return possible object is {@link Integer }
		 * 
		 */
		public Integer getBuildId() {

			return buildId;
		}

		/**
		 * Sets the value of the buildId property.
		 * 
		 * @param value
		 *            allowed object is {@link Integer }
		 * 
		 */
		public void setBuildId( Integer value) {

			this.buildId = value;
		}

		/**
		 * Gets the value of the orientFlip property.
		 * 
		 * @return possible object is {@link Boolean }
		 * 
		 */
		public Boolean isOrientFlip() {

			return orientFlip;
		}

		/**
		 * Sets the value of the orientFlip property.
		 * 
		 * @param value
		 *            allowed object is {@link Boolean }
		 * 
		 */
		public void setOrientFlip( Boolean value) {

			this.orientFlip = value;
		}

	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="ClinicalSignificance" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType( XmlAccessType.FIELD)
	@XmlType( name = "", propOrder = {"clinicalSignificance"})
	public static class Phenotype {

		@XmlElement( name = "ClinicalSignificance")
		protected List<String> clinicalSignificance;

		/**
		 * Gets the value of the clinicalSignificance property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a
		 * snapshot. Therefore any modification you make to the returned list
		 * will be present inside the JAXB object. This is why there is not a
		 * <CODE>set</CODE> method for the clinicalSignificance property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getClinicalSignificance().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list
		 * {@link String }
		 * 
		 * 
		 */
		public List<String> getClinicalSignificance() {

			if( clinicalSignificance == null){
				clinicalSignificance = new ArrayList<String>();
			}
			return this.clinicalSignificance;
		}

	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="Seq5" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
	 *         &lt;element name="Observed" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="Seq3" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
	 *       &lt;/sequence>
	 *       &lt;attribute name="exemplarSs" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
	 *       &lt;attribute name="ancestralAllele" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType( XmlAccessType.FIELD)
	@XmlType( name = "", propOrder = {"seq5", "observed", "seq3"})
	public static class Sequence {

		@XmlElement( name = "Seq5")
		protected String seq5;
		@XmlElement( name = "Observed", required = true)
		protected String observed;
		@XmlElement( name = "Seq3")
		protected String seq3;
		@XmlAttribute( name = "exemplarSs", required = true)
		protected int exemplarSs;
		@XmlAttribute( name = "ancestralAllele")
		protected String ancestralAllele;

		/**
		 * Gets the value of the seq5 property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getSeq5() {

			return seq5;
		}

		/**
		 * Sets the value of the seq5 property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setSeq5( String value) {

			this.seq5 = value;
		}

		/**
		 * Gets the value of the observed property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getObserved() {

			return observed;
		}

		/**
		 * Sets the value of the observed property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setObserved( String value) {

			this.observed = value;
		}

		/**
		 * Gets the value of the seq3 property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getSeq3() {

			return seq3;
		}

		/**
		 * Sets the value of the seq3 property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setSeq3( String value) {

			this.seq3 = value;
		}

		/**
		 * Gets the value of the exemplarSs property.
		 * 
		 */
		public int getExemplarSs() {

			return exemplarSs;
		}

		/**
		 * Sets the value of the exemplarSs property.
		 * 
		 */
		public void setExemplarSs( int value) {

			this.exemplarSs = value;
		}

		/**
		 * Gets the value of the ancestralAllele property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getAncestralAllele() {

			return ancestralAllele;
		}

		/**
		 * Sets the value of the ancestralAllele property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setAncestralAllele( String value) {

			this.ancestralAllele = value;
		}

	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;attribute name="build" type="{http://www.w3.org/2001/XMLSchema}int" />
	 *       &lt;attribute name="date" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType( XmlAccessType.FIELD)
	@XmlType( name = "")
	public static class Update {

		@XmlAttribute( name = "build")
		protected Integer build;
		@XmlAttribute( name = "date")
		protected String date;

		/**
		 * Gets the value of the build property.
		 * 
		 * @return possible object is {@link Integer }
		 * 
		 */
		public Integer getBuild() {

			return build;
		}

		/**
		 * Sets the value of the build property.
		 * 
		 * @param value
		 *            allowed object is {@link Integer }
		 * 
		 */
		public void setBuild( Integer value) {

			this.build = value;
		}

		/**
		 * Gets the value of the date property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getDate() {

			return date;
		}

		/**
		 * Sets the value of the date property.
		 * 
		 * @param value
		 *            allowed object is {@link String }
		 * 
		 */
		public void setDate( String value) {

			this.date = value;
		}

	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="otherPopBatchId" type="{http://www.w3.org/2001/XMLSchema}int" maxOccurs="unbounded" minOccurs="0"/>
	 *         &lt;element name="twoHit2AlleleBatchId" type="{http://www.w3.org/2001/XMLSchema}int" maxOccurs="unbounded" minOccurs="0"/>
	 *         &lt;element name="FrequencyClass" type="{http://www.w3.org/2001/XMLSchema}int" maxOccurs="unbounded" minOccurs="0"/>
	 *         &lt;element name="HapMapPhase" type="{http://www.w3.org/2001/XMLSchema}int" maxOccurs="unbounded" minOccurs="0"/>
	 *         &lt;element name="TGPPhase" type="{http://www.w3.org/2001/XMLSchema}int" maxOccurs="unbounded" minOccurs="0"/>
	 *         &lt;element name="SuspectEvidence" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
	 *       &lt;/sequence>
	 *       &lt;attribute name="byCluster" type="{http://www.w3.org/2001/XMLSchema}boolean" />
	 *       &lt;attribute name="byFrequency" type="{http://www.w3.org/2001/XMLSchema}boolean" />
	 *       &lt;attribute name="byOtherPop" type="{http://www.w3.org/2001/XMLSchema}boolean" />
	 *       &lt;attribute name="by2Hit2Allele" type="{http://www.w3.org/2001/XMLSchema}boolean" />
	 *       &lt;attribute name="byHapMap" type="{http://www.w3.org/2001/XMLSchema}boolean" />
	 *       &lt;attribute name="by1000G" type="{http://www.w3.org/2001/XMLSchema}boolean" />
	 *       &lt;attribute name="suspect" type="{http://www.w3.org/2001/XMLSchema}boolean" />
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType( XmlAccessType.FIELD)
	@XmlType( name = "", propOrder = {"otherPopBatchId", "twoHit2AlleleBatchId", "frequencyClass", "hapMapPhase",
			"tgpPhase", "suspectEvidence"})
	public static class Validation {

		@XmlElement( type = Integer.class)
		protected List<Integer> otherPopBatchId;
		@XmlElement( type = Integer.class)
		protected List<Integer> twoHit2AlleleBatchId;
		@XmlElement( name = "FrequencyClass", type = Integer.class)
		protected List<Integer> frequencyClass;
		@XmlElement( name = "HapMapPhase", type = Integer.class)
		protected List<Integer> hapMapPhase;
		@XmlElement( name = "TGPPhase", type = Integer.class)
		protected List<Integer> tgpPhase;
		@XmlElement( name = "SuspectEvidence")
		protected List<String> suspectEvidence;
		@XmlAttribute( name = "byCluster")
		protected Boolean byCluster;
		@XmlAttribute( name = "byFrequency")
		protected Boolean byFrequency;
		@XmlAttribute( name = "byOtherPop")
		protected Boolean byOtherPop;
		@XmlAttribute( name = "by2Hit2Allele")
		protected Boolean by2Hit2Allele;
		@XmlAttribute( name = "byHapMap")
		protected Boolean byHapMap;
		@XmlAttribute( name = "by1000G")
		protected Boolean by1000G;
		@XmlAttribute( name = "suspect")
		protected Boolean suspect;

		/**
		 * Gets the value of the otherPopBatchId property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a
		 * snapshot. Therefore any modification you make to the returned list
		 * will be present inside the JAXB object. This is why there is not a
		 * <CODE>set</CODE> method for the otherPopBatchId property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getOtherPopBatchId().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list
		 * {@link Integer }
		 * 
		 * 
		 */
		public List<Integer> getOtherPopBatchId() {

			if( otherPopBatchId == null){
				otherPopBatchId = new ArrayList<Integer>();
			}
			return this.otherPopBatchId;
		}

		/**
		 * Gets the value of the twoHit2AlleleBatchId property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a
		 * snapshot. Therefore any modification you make to the returned list
		 * will be present inside the JAXB object. This is why there is not a
		 * <CODE>set</CODE> method for the twoHit2AlleleBatchId property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getTwoHit2AlleleBatchId().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list
		 * {@link Integer }
		 * 
		 * 
		 */
		public List<Integer> getTwoHit2AlleleBatchId() {

			if( twoHit2AlleleBatchId == null){
				twoHit2AlleleBatchId = new ArrayList<Integer>();
			}
			return this.twoHit2AlleleBatchId;
		}

		/**
		 * Gets the value of the frequencyClass property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a
		 * snapshot. Therefore any modification you make to the returned list
		 * will be present inside the JAXB object. This is why there is not a
		 * <CODE>set</CODE> method for the frequencyClass property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getFrequencyClass().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list
		 * {@link Integer }
		 * 
		 * 
		 */
		public List<Integer> getFrequencyClass() {

			if( frequencyClass == null){
				frequencyClass = new ArrayList<Integer>();
			}
			return this.frequencyClass;
		}

		/**
		 * Gets the value of the hapMapPhase property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a
		 * snapshot. Therefore any modification you make to the returned list
		 * will be present inside the JAXB object. This is why there is not a
		 * <CODE>set</CODE> method for the hapMapPhase property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getHapMapPhase().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list
		 * {@link Integer }
		 * 
		 * 
		 */
		public List<Integer> getHapMapPhase() {

			if( hapMapPhase == null){
				hapMapPhase = new ArrayList<Integer>();
			}
			return this.hapMapPhase;
		}

		/**
		 * Gets the value of the tgpPhase property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a
		 * snapshot. Therefore any modification you make to the returned list
		 * will be present inside the JAXB object. This is why there is not a
		 * <CODE>set</CODE> method for the tgpPhase property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getTGPPhase().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list
		 * {@link Integer }
		 * 
		 * 
		 */
		public List<Integer> getTGPPhase() {

			if( tgpPhase == null){
				tgpPhase = new ArrayList<Integer>();
			}
			return this.tgpPhase;
		}

		/**
		 * Gets the value of the suspectEvidence property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a
		 * snapshot. Therefore any modification you make to the returned list
		 * will be present inside the JAXB object. This is why there is not a
		 * <CODE>set</CODE> method for the suspectEvidence property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getSuspectEvidence().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list
		 * {@link String }
		 * 
		 * 
		 */
		public List<String> getSuspectEvidence() {

			if( suspectEvidence == null){
				suspectEvidence = new ArrayList<String>();
			}
			return this.suspectEvidence;
		}

		/**
		 * Gets the value of the byCluster property.
		 * 
		 * @return possible object is {@link Boolean }
		 * 
		 */
		public Boolean isByCluster() {

			return byCluster;
		}

		/**
		 * Sets the value of the byCluster property.
		 * 
		 * @param value
		 *            allowed object is {@link Boolean }
		 * 
		 */
		public void setByCluster( Boolean value) {

			this.byCluster = value;
		}

		/**
		 * Gets the value of the byFrequency property.
		 * 
		 * @return possible object is {@link Boolean }
		 * 
		 */
		public Boolean isByFrequency() {

			return byFrequency;
		}

		/**
		 * Sets the value of the byFrequency property.
		 * 
		 * @param value
		 *            allowed object is {@link Boolean }
		 * 
		 */
		public void setByFrequency( Boolean value) {

			this.byFrequency = value;
		}

		/**
		 * Gets the value of the byOtherPop property.
		 * 
		 * @return possible object is {@link Boolean }
		 * 
		 */
		public Boolean isByOtherPop() {

			return byOtherPop;
		}

		/**
		 * Sets the value of the byOtherPop property.
		 * 
		 * @param value
		 *            allowed object is {@link Boolean }
		 * 
		 */
		public void setByOtherPop( Boolean value) {

			this.byOtherPop = value;
		}

		/**
		 * Gets the value of the by2Hit2Allele property.
		 * 
		 * @return possible object is {@link Boolean }
		 * 
		 */
		public Boolean isBy2Hit2Allele() {

			return by2Hit2Allele;
		}

		/**
		 * Sets the value of the by2Hit2Allele property.
		 * 
		 * @param value
		 *            allowed object is {@link Boolean }
		 * 
		 */
		public void setBy2Hit2Allele( Boolean value) {

			this.by2Hit2Allele = value;
		}

		/**
		 * Gets the value of the byHapMap property.
		 * 
		 * @return possible object is {@link Boolean }
		 * 
		 */
		public Boolean isByHapMap() {

			return byHapMap;
		}

		/**
		 * Sets the value of the byHapMap property.
		 * 
		 * @param value
		 *            allowed object is {@link Boolean }
		 * 
		 */
		public void setByHapMap( Boolean value) {

			this.byHapMap = value;
		}

		/**
		 * Gets the value of the by1000G property.
		 * 
		 * @return possible object is {@link Boolean }
		 * 
		 */
		public Boolean isBy1000G() {

			return by1000G;
		}

		/**
		 * Sets the value of the by1000G property.
		 * 
		 * @param value
		 *            allowed object is {@link Boolean }
		 * 
		 */
		public void setBy1000G( Boolean value) {

			this.by1000G = value;
		}

		/**
		 * Gets the value of the suspect property.
		 * 
		 * @return possible object is {@link Boolean }
		 * 
		 */
		public Boolean isSuspect() {

			return suspect;
		}

		/**
		 * Sets the value of the suspect property.
		 * 
		 * @param value
		 *            allowed object is {@link Boolean }
		 * 
		 */
		public void setSuspect( Boolean value) {

			this.suspect = value;
		}

	}

}
